namespace Thermodynamics.Generator;

static class CommandManagerSource
{
    const string NAMESPACE_PLACEHOLDER = "__COMMAND_MANAGER_NAMESPACE__";

    public static string BuildSource(string commandManagerNamespace) =>
        SourceTemplate.Replace(NAMESPACE_PLACEHOLDER, commandManagerNamespace);

    const string SourceTemplate = """
// <auto-generated/>
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Sandbox.ModAPI;
using VRage;
using VRage.Game;
using VRage.Game.Components;
using VRage.Utils;
using VRageMath;

namespace __COMMAND_MANAGER_NAMESPACE__
{
	[MySessionComponentDescriptor(MyUpdateOrder.NoUpdate, 0)]
	public sealed partial class CommandManager : MySessionComponentBase
	{
		sealed class ChatCommandParameterDefinition
		{
			public readonly string Name;
			public readonly Type Type;
			public readonly Type ValueType;
			public readonly bool Optional;
			public readonly object DefaultValue;

			public ChatCommandParameterDefinition(string name, Type type)
				: this(name, type, type, false, null)
			{
			}

			public ChatCommandParameterDefinition(string name, Type type, Type valueType, bool optional)
				: this(name, type, valueType, optional, null)
			{
			}

			public ChatCommandParameterDefinition(
				string name,
				Type type,
				Type valueType,
				bool optional,
				object defaultValue)
			{
				Name = name;
				Type = type;
				ValueType = valueType ?? type;
				Optional = optional;
				DefaultValue = defaultValue;
			}
		}

		sealed class ChatCommandDefinition
		{
			public readonly string Group;
			public readonly string Name;
			public readonly string Meta;
			public readonly string LocKey;
			public readonly Action<string[]> Callback;
			public readonly Action<object[]> TypedCallback;
			public readonly ChatCommandParameterDefinition[] Parameters;
			public readonly int ArgsRequired;

			public ChatCommandDefinition(
				string group,
				string name,
				string meta,
				string locKey,
				Action<string[]> callback,
				int argsRequired)
			{
				Group = group;
				Name = name;
				Meta = meta;
				LocKey = locKey;
				Callback = callback;
				ArgsRequired = argsRequired;
			}

			public ChatCommandDefinition(
				string group,
				string name,
				string meta,
				string locKey,
				ChatCommandParameterDefinition[] parameters,
				Action<object[]> callback,
				int argsRequired)
			{
				Group = group;
				Name = name;
				Meta = meta;
				LocKey = locKey;
				Parameters = parameters ?? new ChatCommandParameterDefinition[0];
				TypedCallback = callback;
				ArgsRequired = argsRequired < 0 ? CountRequiredArguments(Parameters) : argsRequired;
			}
		}

		sealed class CmdGroupInitializer : IReadOnlyList<ChatCommandDefinition>
		{
			public ChatCommandDefinition this[int index] { get { return _data[index]; } }
			public int Count { get { return _data.Count; } }
			public string DefaultGroup { get; private set; }

			private readonly List<ChatCommandDefinition> _data;

			public CmdGroupInitializer(int capacity = 0)
			{
				_data = new List<ChatCommandDefinition>(capacity);
			}

			public void SetDefaultGroup(string group)
			{
				DefaultGroup = group;
			}

			public void Add(string cmdName, string meta, string locKey, Action<string[]> callback, int argsRequrired = 0)
			{
				AddToGroup(DefaultGroup, cmdName, meta, locKey, callback, argsRequrired);
			}

			public void AddToGroup(
				string group,
				string cmdName,
				string meta,
				string locKey,
				Action<string[]> callback,
				int argsRequrired = 0)
			{
				_data.Add(new ChatCommandDefinition(group, cmdName, meta, locKey, callback, argsRequrired));
			}

			public void AddTyped(
				string cmdName,
				string meta,
				string locKey,
				ChatCommandParameterDefinition[] parameters,
				Action<object[]> callback,
				int argsRequrired = -1)
			{
				AddTypedToGroup(DefaultGroup, cmdName, meta, locKey, parameters, callback, argsRequrired);
			}

			public void AddTypedToGroup(
				string group,
				string cmdName,
				string meta,
				string locKey,
				ChatCommandParameterDefinition[] parameters,
				Action<object[]> callback,
				int argsRequrired = -1)
			{
				_data.Add(new ChatCommandDefinition(group, cmdName, meta, locKey, parameters, callback, argsRequrired));
			}

			public IEnumerator<ChatCommandDefinition> GetEnumerator()
			{
				return _data.GetEnumerator();
			}

			IEnumerator IEnumerable.GetEnumerator()
			{
				return _data.GetEnumerator();
			}
		}

		private static CommandManager _instance;
		private readonly Regex _cmdParser;
		private readonly List<CommandGroup> _commandGroups;
		private readonly Dictionary<string, Command> _commands;
		private string _modName;

		public CommandManager()
		{
			if (_instance == null)
				_instance = this;
			else
				throw new Exception("Only one instance of CommandManager can exist at any given time.");

			_commandGroups = new List<CommandGroup>();
			_commands = new Dictionary<string, Command>();
			_cmdParser = new Regex(@"((\s*?[\s,;|]\s*?)(([^,\s;|\""]+)|("".+"")))+");
		}

		public override void Init(MyObjectBuilder_SessionComponent sessionComponent)
		{
			base.Init(sessionComponent);
			_modName = ResolveModName();
			BuildChatCommands();
			MyAPIGateway.Utilities.MessageEnteredSender += MessageHandler;
		}

		protected override void UnloadData()
		{
			MyAPIGateway.Utilities.MessageEnteredSender -= MessageHandler;
			_instance = null;
		}

		string ResolveModName()
		{
			if (ModContext != null && !string.IsNullOrWhiteSpace(ModContext.ModName))
				return ModContext.ModName;

			return "Chat Commands";
		}

		static string MessageSource
		{
			get
			{
				if (_instance != null && !string.IsNullOrWhiteSpace(_instance._modName))
					return _instance._modName;

				return "Chat Commands";
			}
		}

		public static string GetReport()
		{
			if (_instance == null)
				return string.Empty;

			var builder = new StringBuilder();
			for (int i = 0; i < _instance._commandGroups.Count; i++)
			{
				var group = _instance._commandGroups[i];
				if (group != null)
					group.AppendReport(builder);
			}

			return builder.ToString();
		}

		static CommandGroup GetOrCreateGroup(string prefix, CmdGroupInitializer groupInitializer = null)
		{
			string displayPrefix = NormalizeDisplayPrefix(prefix);
			prefix = NormalizePrefix(prefix);
			if (_instance == null || string.IsNullOrWhiteSpace(prefix))
				return null;

			CommandGroup group = _instance._commandGroups.Find(x => x.Prefix == prefix);

			if (group == null)
			{
				group = new CommandGroup(prefix, displayPrefix);
				_instance._commandGroups.Add(group);
				group.AddCommands(groupInitializer);
			}

			return group;
		}

		static void AddCommands(CmdGroupInitializer commands)
		{
			if (_instance == null || commands == null)
				return;

			for (int n = 0; n < commands.Count; n++)
			{
				var command = commands[n];
				if (command == null)
					continue;

				var group = GetOrCreateGroup(command.Group ?? commands.DefaultGroup);
				if (group == null)
					continue;

				if (command.TypedCallback != null)
					group.TryAddTyped(command.Name, command.Meta, command.LocKey, command.Parameters, command.TypedCallback, command.ArgsRequired);
				else
					group.TryAdd(command.Name, command.Meta, command.LocKey, command.Callback, command.ArgsRequired);
			}
		}

		static string NormalizePrefix(string prefix)
		{
			if (string.IsNullOrWhiteSpace(prefix))
				return prefix;

			prefix = prefix.Trim();
			if (prefix.Length > 0 && prefix[0] != '/')
				prefix = "/" + prefix;

			return prefix.ToLowerInvariant();
		}

		static string NormalizeDisplayPrefix(string prefix)
		{
			if (string.IsNullOrWhiteSpace(prefix))
				return prefix;

			prefix = prefix.Trim();
			if (prefix.Length > 0 && prefix[0] != '/')
				prefix = "/" + prefix;

			return prefix;
		}

		static string GetLoc(string key)
		{
			if (string.IsNullOrWhiteSpace(key))
				return null;

			return MyTexts.Get(MyStringId.GetOrCompute(key)).ToString();
		}

		private void MessageHandler(ulong sender, string message, ref bool sendToOthers)
		{
			message = message.ToLower();
			CommandGroup group = _commandGroups.Find(x => message.StartsWith(x.Prefix));

			if (group != null)
			{
				sendToOthers = false;
				try
				{
					group.TryRunCommand(message);
				}
				catch (Exception e)
				{
					MyAPIGateway.Utilities.ShowMessage(MessageSource, "Command failed: " + e.Message);
					throw;
				}
			}
		}

		private static bool TryParseCommand(string cmd, out string[] matches)
		{
			Match match = _instance._cmdParser.Match(cmd);
			CaptureCollection captures = match.Groups[3].Captures;
			matches = new string[captures.Count];

			for (int n = 0; n < captures.Count; n++)
			{
				matches[n] = captures[n].Value;

				if (matches[n][0] == '"' && matches[n][matches[n].Length - 1] == '"')
					matches[n] = matches[n].Substring(1, matches[n].Length - 2);
			}

			return matches.Length > 0;
		}

		private class CommandGroup
		{
			public string Prefix { get; private set; }
			public string DisplayPrefix { get; private set; }

			private readonly List<Command> _commands;

			public CommandGroup(string prefix, string displayPrefix)
			{
				_commands = new List<Command>();
				Prefix = prefix;
				DisplayPrefix = string.IsNullOrWhiteSpace(displayPrefix) ? prefix : displayPrefix;
			}

			public void TryRunCommand(string message)
			{
				bool cmdFound = false;
				string[] matches;

				if (TryParseCommand(message, out matches))
				{
					string cmdName = matches[0];
					Command command;

					if (_instance._commands.TryGetValue(Prefix + "." + cmdName, out command))
					{
						string[] args = GetSubarray(matches, 1);
						cmdFound = true;

						if (args.Length >= command.ArgsRequired)
							command.InvokeCommand(args);
					}
				}

				if (!cmdFound)
				{
					var sb = new StringBuilder("Available commands:");

					foreach (var command in _instance._commands)
						sb.Append('"').Append(command.Key.Replace('.', ' ')).Append("\", ");

					MyAPIGateway.Utilities.ShowMessage(MessageSource, "Command not recognised.\n" + sb.ToString().TrimEnd(',', ' '));
				}
			}

			public bool TryAdd(string name, string meta, string locKey, Action<string[]> callback, int argsRequired = 0)
			{
				string displayName = name;
				name = name.ToLower();
				string key = Prefix + "." + name;

				if (_instance != null && !_instance._commands.ContainsKey(key))
				{
					Command command = new Command(displayName, meta, locKey, callback, argsRequired);
					_commands.Add(command);
					_instance._commands.Add(key, command);
					return true;
				}

				return false;
			}

			public bool TryAddTyped(
				string name,
				string meta,
				string locKey,
				ChatCommandParameterDefinition[] parameters,
				Action<object[]> callback,
				int argsRequired = -1)
			{
				string displayName = name;
				name = name.ToLower();
				string key = Prefix + "." + name;

				if (_instance != null && !_instance._commands.ContainsKey(key))
				{
					Command command = new Command(displayName, meta, locKey, parameters, callback, argsRequired);
					_commands.Add(command);
					_instance._commands.Add(key, command);
					return true;
				}

				return false;
			}

			public void AddCommands(CmdGroupInitializer newCommands)
			{
				if (newCommands == null)
					return;

				for (int n = 0; n < newCommands.Count; n++)
				{
					var cmd = newCommands[n];
					if (cmd == null)
						continue;

					if (!string.IsNullOrWhiteSpace(cmd.Group) &&
						NormalizePrefix(cmd.Group) != Prefix)
					{
						continue;
					}

					if (cmd.TypedCallback != null)
						TryAddTyped(cmd.Name, cmd.Meta, cmd.LocKey, cmd.Parameters, cmd.TypedCallback, cmd.ArgsRequired);
					else
						TryAdd(cmd.Name, cmd.Meta, cmd.LocKey, cmd.Callback, cmd.ArgsRequired);
				}
			}

			public static T[] GetSubarray<T>(T[] arr, int start)
			{
				var result = new T[arr.Length - start];
				Array.Copy(arr, start, result, 0, result.Length);
				return result;
			}

			public void AppendReport(StringBuilder builder)
			{
				if (builder == null)
					return;

				for (int i = 0; i < _commands.Count; i++)
				{
					var command = _commands[i];
					if (command == null)
						continue;

					builder.Append(DisplayPrefix).Append(' ').Append(command.CmdName);
					command.AppendParameterReport(builder);
					builder.Append('\n');

					var meta = command.GetReportMeta();
					if (!string.IsNullOrWhiteSpace(meta))
						builder.Append(meta);

					builder.Append('\n').Append('\n');
				}
			}
		}

		private class Command
		{
			readonly Action<string[]> _callback;
			readonly Action<object[]> _typedCallback;
			readonly ChatCommandParameterDefinition[] _parameters;

			public string CmdName { get; private set; }
			public string Meta { get; private set; }
			public string LocKey { get; private set; }
			public int ArgsRequired { get; private set; }

			public Command(string cmdName, string meta, string locKey, Action<string[]> callback, int argsRequired)
			{
				CmdName = cmdName;
				Meta = meta;
				LocKey = locKey;
				ArgsRequired = argsRequired;
				_callback = callback;
				_parameters = new ChatCommandParameterDefinition[0];
			}

			public Command(
				string cmdName,
				string meta,
				string locKey,
				ChatCommandParameterDefinition[] parameters,
				Action<object[]> typedCallback,
				int argsRequired)
			{
				CmdName = cmdName;
				Meta = meta;
				LocKey = locKey;
				ArgsRequired = argsRequired;
				_parameters = parameters ?? new ChatCommandParameterDefinition[0];
				_typedCallback = typedCallback;
				if (ArgsRequired < 0)
					ArgsRequired = CountRequiredArguments(_parameters);
			}

			public void InvokeCommand(string[] args)
			{
				if (_typedCallback == null)
				{
					if (_callback != null)
						_callback(args);
					return;
				}

				object[] values;
				string error;
				if (!ChatCommandParameterResolver.TryResolve(args, _parameters, out values, out error))
				{
					MyAPIGateway.Utilities.ShowMessage(MessageSource, error);
					return;
				}

				_typedCallback(values);
			}

			public void AppendParameterReport(StringBuilder builder)
			{
				if (builder == null || _parameters == null)
					return;

				for (int i = 0; i < _parameters.Length; i++)
				{
					var parameter = _parameters[i];
					if (parameter == null)
						continue;

					builder.Append(' ').Append(GetReportTypeName(parameter));
				}
			}

			public string GetReportMeta()
			{
				if (!string.IsNullOrWhiteSpace(LocKey))
				{
					var localized = GetLoc(LocKey);
					if (!string.IsNullOrWhiteSpace(localized))
						return localized;
				}

				return Meta;
			}
		}

		static string GetReportTypeName(ChatCommandParameterDefinition parameter)
		{
			if (parameter == null || parameter.Type == null)
				return "object";

			var name = GetReportTypeName(parameter.ValueType ?? parameter.Type);
			if (parameter.Optional && name.Length > 0 && name[name.Length - 1] != '?')
				name += "?";

			return name;
		}

		static string GetReportTypeName(Type type)
		{
			if (type == null)
				return "object";

			if (type == typeof(bool))
				return "bool";

			if (type == typeof(string))
				return "string";

			if (type == typeof(int))
				return "int";

			if (type == typeof(long))
				return "long";

			if (type == typeof(float))
				return "float";

			if (type == typeof(double))
				return "double";

			if (type == typeof(Color))
				return "Color";

			return type.Name;
		}

		static int CountRequiredArguments(ChatCommandParameterDefinition[] parameters)
		{
			if (parameters == null || parameters.Length == 0)
				return 0;

			var required = 0;
			for (int i = 0; i < parameters.Length; i++)
				if (parameters[i] != null && !parameters[i].Optional)
					required++;

			return required;
		}

		static class ChatCommandParameterResolver
		{
			public static bool TryResolve(
				string[] args,
				ChatCommandParameterDefinition[] parameters,
				out object[] values,
				out string error)
			{
				args = args ?? new string[0];
				parameters = parameters ?? new ChatCommandParameterDefinition[0];
				values = new object[parameters.Length];
				error = null;

				var index = 0;
				for (int i = 0; i < parameters.Length; i++)
				{
					var parameter = parameters[i];
					int consumed;
					object value;
					if (!TryResolveParameter(
						    args,
						    index,
						    parameters.Length - i - 1,
						    parameter,
						    out value,
						    out consumed,
						    out error))
					{
						values = null;
						return false;
					}

					values[i] = value;
					index += consumed;
				}

				if (index != args.Length)
				{
					error = "Too many command arguments.";
					values = null;
					return false;
				}

				return true;
			}

			static bool TryResolveParameter(
				string[] args,
				int index,
				int remainingParameters,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				if (parameter == null || parameter.Type == null)
				{
					error = "Command parameter metadata is invalid.";
					return false;
				}

				var targetType = parameter.ValueType ?? parameter.Type;

				if (index >= args.Length)
				{
					if (parameter.Optional)
					{
						value = parameter.DefaultValue;
						return true;
					}

					error = "Missing value for command parameter '" + DisplayParameterName(parameter) + "'.";
					return false;
				}

				if (targetType == typeof(string))
				{
					consumed = remainingParameters == 0 ? args.Length - index : 1;
					value = consumed == 1
						? args[index]
						: string.Join(" ", args, index, consumed);
					return true;
				}

				if (targetType == typeof(bool))
					return TryResolveBool(args[index], parameter, out value, out consumed, out error);

				if (targetType == typeof(int))
					return TryResolveInt(args[index], parameter, out value, out consumed, out error);

				if (targetType == typeof(long))
					return TryResolveLong(args[index], parameter, out value, out consumed, out error);

				if (targetType == typeof(float))
					return TryResolveFloat(args[index], parameter, out value, out consumed, out error);

				if (targetType == typeof(double))
					return TryResolveDouble(args[index], parameter, out value, out consumed, out error);

				if (targetType == typeof(Color))
					return TryResolveColor(args, index, remainingParameters, parameter, out value, out consumed, out error);

				error = "Unsupported command parameter type '" + parameter.Type.Name + "' for '" +
				        DisplayParameterName(parameter) + "'.";
				return false;
			}

			static bool TryResolveBool(
				string token,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				bool parsed;
				if (TryParseBoolean(token, out parsed))
				{
					value = parsed;
					consumed = 1;
					return true;
				}

				error = "Invalid value for '" + DisplayParameterName(parameter) +
				        "'. Expected true/false, on/off, yes/no, or 1/0.";
				return false;
			}

			static bool TryResolveInt(
				string token,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				int parsed;
				if (int.TryParse(token, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsed))
				{
					value = parsed;
					consumed = 1;
					return true;
				}

				error = "Invalid integer value for '" + DisplayParameterName(parameter) + "'.";
				return false;
			}

			static bool TryResolveLong(
				string token,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				long parsed;
				if (long.TryParse(token, NumberStyles.Integer, CultureInfo.InvariantCulture, out parsed))
				{
					value = parsed;
					consumed = 1;
					return true;
				}

				error = "Invalid integer value for '" + DisplayParameterName(parameter) + "'.";
				return false;
			}

			static bool TryResolveFloat(
				string token,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				float parsed;
				if (float.TryParse(token, NumberStyles.Float, CultureInfo.InvariantCulture, out parsed))
				{
					value = parsed;
					consumed = 1;
					return true;
				}

				error = "Invalid number value for '" + DisplayParameterName(parameter) + "'.";
				return false;
			}

			static bool TryResolveDouble(
				string token,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				double parsed;
				if (double.TryParse(token, NumberStyles.Float, CultureInfo.InvariantCulture, out parsed))
				{
					value = parsed;
					consumed = 1;
					return true;
				}

				error = "Invalid number value for '" + DisplayParameterName(parameter) + "'.";
				return false;
			}

			static bool TryResolveColor(
				string[] args,
				int index,
				int remainingParameters,
				ChatCommandParameterDefinition parameter,
				out object value,
				out int consumed,
				out string error)
			{
				value = null;
				consumed = 0;
				error = null;

				Color color;
				if (TryParseHexColor(args[index], out color))
				{
					value = color;
					consumed = 1;
					return true;
				}

				if (index + 3 <= args.Length &&
				    args.Length - (index + 3) >= remainingParameters &&
				    TryParseRgb(args[index], args[index + 1], args[index + 2], out color))
				{
					value = color;
					consumed = 3;
					return true;
				}

				if (index + 4 <= args.Length &&
				    args.Length - (index + 4) >= remainingParameters &&
				    string.Equals(args[index], "hsv", StringComparison.OrdinalIgnoreCase) &&
				    TryParseHsv(args[index + 1], args[index + 2], args[index + 3], out color))
				{
					value = color;
					consumed = 4;
					return true;
				}

				error = "Invalid color value for '" + DisplayParameterName(parameter) +
				        "'. Expected #rgb, #rrggbb, r g b, or hsv h s v.";
				return false;
			}

			static bool TryParseHexColor(string value, out Color color)
			{
				color = new Color(255, 255, 255);

				if (string.IsNullOrWhiteSpace(value))
					return false;

				var hex = value.Trim();

				if (hex[0] == '#')
					hex = hex.Substring(1);

				if (hex.Length == 3)
				{
					hex = string.Concat(
						hex[0], hex[0],
						hex[1], hex[1],
						hex[2], hex[2]);
				}
				else if (hex.Length != 6)
				{
					return false;
				}

				byte r;
				byte g;
				byte b;
				if (!byte.TryParse(hex.Substring(0, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out r) ||
				    !byte.TryParse(hex.Substring(2, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out g) ||
				    !byte.TryParse(hex.Substring(4, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out b))
				{
					return false;
				}

				color = new Color(r, g, b);
				return true;
			}

			static bool TryParseBoolean(string value, out bool result)
			{
				result = false;
				if (string.IsNullOrWhiteSpace(value))
					return false;

				switch (value.Trim().ToLowerInvariant())
				{
					case "true":
					case "on":
					case "yes":
					case "1":
						result = true;
						return true;
					case "false":
					case "off":
					case "no":
					case "0":
						result = false;
						return true;
					default:
						return false;
				}
			}

			static bool TryParseRgb(string rToken, string gToken, string bToken, out Color color)
			{
				color = Color.White;
				int r;
				int g;
				int b;
				if (!int.TryParse(rToken, NumberStyles.Integer, CultureInfo.InvariantCulture, out r) ||
				    !int.TryParse(gToken, NumberStyles.Integer, CultureInfo.InvariantCulture, out g) ||
				    !int.TryParse(bToken, NumberStyles.Integer, CultureInfo.InvariantCulture, out b) ||
				    r < 0 || r > 255 ||
				    g < 0 || g > 255 ||
				    b < 0 || b > 255)
				{
					return false;
				}

				color = new Color((byte)r, (byte)g, (byte)b);
				return true;
			}

			static bool TryParseHsv(string hToken, string sToken, string vToken, out Color color)
			{
				color = Color.White;
				float h;
				float s;
				float v;
				if (!float.TryParse(hToken, NumberStyles.Float, CultureInfo.InvariantCulture, out h) ||
				    !float.TryParse(sToken, NumberStyles.Float, CultureInfo.InvariantCulture, out s) ||
				    !float.TryParse(vToken, NumberStyles.Float, CultureInfo.InvariantCulture, out v))
				{
					return false;
				}

				if (h > 1f && h <= 360f)
					h /= 360f;

				if (h < 0f || h > 1f || s < 0f || s > 1f || v < 0f || v > 1f)
					return false;

				color = new Vector3(h, s, v).HSVtoColor();
				return true;
			}

			static string DisplayParameterName(ChatCommandParameterDefinition parameter)
			{
				if (parameter == null || string.IsNullOrWhiteSpace(parameter.Name))
					return "value";

				return parameter.Name;
			}
		}
	}
}
""";
}
