using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Thermodynamics.Generator;

[Generator]
public sealed class GeneratedConstants : IIncrementalGenerator
{
    const string DEFAULT_VERSION = "0.0.0";
    const string DEFAULT_CONFIGURATION = "Unknown";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => new BuildConstants(
                GetGlobalOption(options, "build_property.Version", DEFAULT_VERSION),
                GetGlobalOption(options, "build_property.Configuration", DEFAULT_CONFIGURATION)));

        context.RegisterSourceOutput(optionsProvider, static (spc, constants) =>
        {
            spc.AddSource("Generated.Constants.g.cs", BuildSource(constants));
        });
    }

    static string GetGlobalOption(AnalyzerConfigOptionsProvider options, string key, string fallback)
    {
        string value;
        return options.GlobalOptions.TryGetValue(key, out value) && !string.IsNullOrWhiteSpace(value)
            ? value.Trim()
            : fallback;
    }

    static string BuildSource(BuildConstants constants)
    {
        var version = EscapeString(constants.Version);
        var buildConfiguration = EscapeString(constants.BuildConfiguration);
        var versionName = EscapeString(constants.Version + " " + constants.BuildConfiguration + " " +
                                       DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"));

        return @"// <auto-generated/>
namespace Generated
{
    public static class Constants
    {
        public static readonly global::System.Version Version = new global::System.Version(""" + version + @""");
        public const string BuildConfiguration = """ + buildConfiguration + @""";
        public const string VersionName = """ + versionName + @""";
    }
}";
    }

    static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    readonly struct BuildConstants
    {
        public readonly string Version;
        public readonly string BuildConfiguration;

        public BuildConstants(string version, string buildConfiguration)
        {
            Version = version;
            BuildConfiguration = buildConfiguration;
        }
    }
}
